name: Release Components
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN}}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get commit info
        id: commit
        run: |
          echo "::set-output name=user_name::$(git log -1 --pretty=format:'%an')"
          echo "::set-output name=user_email::$(git log -1 --pretty=format:'%ae')"
      - name: Initialize Bit
        uses: bit-tasks/init@v1
      - name: Bit Import and Checkout
        run: |
          bit import
          bit checkout head
      - name: Bit Tag and Export
        uses: bit-tasks/tag-export@v1
      - name: Commit Bitmap
        uses: bit-tasks/commit-bitmap@v1
        with:
          git-user-name: ${{ steps.commit.outputs.user_name }}
          git-user-email: ${{ steps.commit.outputs.user_email }}
