name: Sync Component Version
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'cosmos-cruises/marketing' # Source repo
          token: ${{ secrets.GITHUB_TOKEN }} # Make sure this token has write access to the source repo
          path: 'source-repo'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install json5

      - name: Get the app version from source repo
        id: get_version
        run: |
          cd source-repo
          APP_VERSION=$(python -c "import json5; with open('.bitmap', 'r') as f: data = json5.load(f); print(data['forever-mars-app']['version'])")
          echo "App Version: ${APP_VERSION}"
          echo "::set-output name=version::${APP_VERSION}"

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: 'cosmos-cruises/booking' # Target repo
          token: ${{ secrets.GITHUB_TOKEN }} # Make sure this token has write access to the target repo
          path: 'target-repo'

      - name: Update the app version in target repo
        run: |
          cd target-repo
          python -c "import json5; with open('.bitmap', 'r+') as f: data = json5.load(f); data['forever-mars-app']['version'] = '${{ steps.get_version.outputs.version }}'; f.seek(0); json5.dump(data, f); f.truncate()"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .bitmap
          git commit -m "Sync app version"
          git push origin main
